language: cpp
os:
  - osx
  - linux
osx_image: xcode7.2
sudo: required
dist: trusty

cache:
  directories:
    - .electron
    - node_modules

before_install:
  - "export DISPLAY=:99.0"
  - source scripts/bootstrap.sh
  - sleep 3

install:
  - nvm --version
  - nvm install 6.2
  - node --version
  - npm --version
  - npm install --progress false --depth 0

script:
  - npm test

branches:
  only:
    - master
